### ISSUE TITLE
hypen doesn't work with negative numbers

### ISSUE THREAD

**Issue by pank** [xwl/electric-spacing#10]
Hi,

I want to get:

```
[1,2,3][0:-1]
```

When I type this in with `electric-spacing` I get:

```
[1, 2, 3][0:- 1]
```

Thanks,
Rasmus

PS: Do you prefer the github tracker or `report-emacs-bug`?

**Comment by xwl** [comment]
Github is fine. Which major-mode are you using?

pank notifications@github.com schrieb am Mo., 10. Aug. 2015 um 15:52:

**Comment by pank** [comment]
Python mode in Emacs. Though at the time I just added electric spacing to the prog mode hook.

**Comment by davidshepherd7** [comment]
In case it's useful: [electric operator](https://github.com/davidshepherd7/electric-operator) handles negative slices correctly. It would also be easy to customise for that comma spacing behaviour without needing to modify the source code.

@xwl Sorry if it seems like I'm trying to poach your users! I'm still getting email notifications for issues here and it seems silly not to respond if I can help out. I'll 'unwatch' this repository now so I won't do it again :)

**Comment by xwl** [comment]
Fixed in https://github.com/xwl/electric-spacing/commit/f14e7b8f3768c4efe544d6b5279e73f310b0ba3a
