### ISSUE TITLE
Comma isn't putting space after

### ISSUE THREAD

**Issue by walmes** [xwl/electric-spacing#12]
Hi,

I'm using your package a few days. I like it a lot.
I'm trying accommodate the R style when using ess-mode in emacs. I'll ask you a pull request in the future.
When I was doing tests with the functionalities, I notice that comma isn't working as expected.
I did some tests and I conclude that this `(?, . electric-spacing-\,)` isn't calling `electric-spacing-\,` when `,` is pressed. As a prove, I replaced `?,` by `?+` and commas with space were inserted when `+` were pressed. So, the problem is not about function implementation but key binding. Do you have any suggestion to fix this?

**Comment by xwl** [comment]
I think most likely some other modes have overriden the key ",", have you tried M-x describe-key ?

**Comment by walmes** [comment]
You are completely right. `describe-key` showed that comma is related to `ess-smart-comma`, a function defined in the major mode (ess-mode) active when buffer is an R script or any file associated with ess-mode. I read the documentation and when using `(setq ess-smart-operators t)`, electric comma is enabled by the major mode. So, it rewrites `electric-spacings` minor mode.
