### ISSUE TITLE
Byte compiling fails when installing from MELPA

### ISSUE THREAD

**Issue by gergelypolonkai** [xwl/electric-spacing#21]
When I install from MELPA, the byte compiler reports unbalanced parentheses. Changing the new `?(` to `?\(` seems to fix the problem, although I couldn’t thoroughly test the solution.

**Comment by jasonm23** [comment]
`?\(` is the correct pattern.

**Comment by jasonm23** [comment]
Fixed in #22 please merge.

**Comment by xwl** [comment]
merged, thanks.
